name: Deploy to AWS

on:
  push:
    branches:
      - development

jobs:
  run_test:
    name: Unit Test
    runs-on: ubuntu-18.04
    steps:
      - run: echo "Unit Test Running..."
      - uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Maven Verify
        run: mvn -Ptest clean verify
      - name: Login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          file: coverage.dockerfile
          context: .
          push: true
          tags: rofiksupriant/office-order-coverage:latest
  build:
    name: Build
    runs-on: ubuntu-18.04
    needs: run_test
    steps:
      - run: echo "Starting build package"
      - uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Maven Build
        run: mvn clean package -Dmaven.test.skip=true
      - name: Login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: rofiksupriant/office-order:latest
  deployment:
    name: Deploy container using SSH
    runs-on: ubuntu-18.04
    needs: build
    steps:
      - run: echo "Deploying.."
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_SSH_HOST }}
          port: 22
          username: ${{ secrets.EC2_SSH_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            docker stop office-order office-order-coverage
            docker rmi rofiksupriant/office-order:latest rofiksupriant/office-order-coverage:latest
            docker pull rofiksupriant/office-order:latest
            docker pull rofiksupriant/office-order-coverage:latest
            docker run -d --rm --name office-order-coverage -p 8000:80 rofiksupriant/office-order-coverage:latest
            docker run -d --rm --name office-order -p 8080:8080 --env-file=dev.env --network kampus_merdeka -v /office-order/files:/office-order/files rofiksupriant/office-order:latest
